# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Herschel
tagline:          'Component Pascal x64 compiler'
description:      'Component Pascal x64 compiler for BlackBox Component Builder.'
url:              https://github.com/adimetrius/Cp64
baseurl:          /

author:
  name:           'Anton Dmitriev'
  url:            https://github.com/adimetrius

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adimetrius/Cp64
